import type { WorkflowConfig } from '@/types/workflow'

/** The afwan-api /workflow/config response (steps 1–6), for tests. */
export const WORKFLOW_CONFIG: WorkflowConfig = {
  steps: [
    {
      key: 'passport',
      label: 'Passport',
      short_label: 'Passport',
      order: 1,
      enabled: true,
      statuses: [],
      fields: [],
      warning_days: null,
    },
    {
      key: 'medical',
      label: 'Medical',
      short_label: 'Medical',
      order: 2,
      enabled: true,
      statuses: [
        { value: 'fit', label: 'Fit' },
        { value: 'unfit', label: 'Unfit' },
      ],
      fields: [],
      warning_days: null,
    },
    {
      key: 'calling',
      label: 'Calling / Work Permit',
      short_label: 'Calling',
      order: 3,
      enabled: true,
      statuses: [
        { value: 'in_process', label: 'Applied' },
        { value: 'completed', label: 'Approved' },
        { value: 'rejected', label: 'Rejected' },
      ],
      fields: [
        {
          name: 'reference_no',
          label: 'Permit / calling number',
          type: 'text',
          max: 100,
          in_details: false,
          required_for: ['completed'],
        },
        {
          name: 'step_date',
          label: 'Date',
          type: 'date',
          max: null,
          in_details: false,
          required_for: ['in_process', 'completed', 'rejected'],
        },
        {
          name: 'valid_until',
          label: 'Valid until',
          type: 'date',
          max: null,
          in_details: false,
          required_for: [],
        },
      ],
      warning_days: 30,
    },
    {
      key: 'visa',
      label: 'Visa',
      short_label: 'Visa',
      order: 4,
      enabled: true,
      statuses: [
        { value: 'in_process', label: 'Submitted' },
        { value: 'completed', label: 'Visa issued' },
        { value: 'rejected', label: 'Rejected' },
      ],
      fields: [
        {
          name: 'reference_no',
          label: 'Visa number',
          type: 'text',
          max: 100,
          in_details: false,
          required_for: ['completed'],
        },
        {
          name: 'step_date',
          label: 'Date',
          type: 'date',
          max: null,
          in_details: false,
          required_for: ['in_process', 'completed', 'rejected'],
        },
        {
          name: 'valid_until',
          label: 'Valid until',
          type: 'date',
          max: null,
          in_details: false,
          required_for: [],
        },
      ],
      warning_days: 30,
    },
    {
      key: 'bmet',
      label: 'BMET Clearance',
      short_label: 'BMET',
      order: 5,
      enabled: true,
      statuses: [
        { value: 'in_process', label: 'Submitted' },
        { value: 'completed', label: 'Cleared' },
        { value: 'rejected', label: 'Rejected' },
      ],
      fields: [
        {
          name: 'reference_no',
          label: 'Clearance number',
          type: 'text',
          max: 100,
          in_details: false,
          required_for: ['completed'],
        },
        {
          name: 'step_date',
          label: 'Date',
          type: 'date',
          max: null,
          in_details: false,
          required_for: ['in_process', 'completed', 'rejected'],
        },
        {
          name: 'training_certificate_date',
          label: 'Training certificate date',
          type: 'date',
          max: null,
          in_details: true,
          required_for: [],
          not_future_for: ['in_process', 'completed', 'rejected'],
        },
        {
          name: 'finger_date',
          label: 'Finger date',
          type: 'date',
          max: null,
          in_details: true,
          required_for: [],
          not_future_for: ['in_process', 'completed', 'rejected'],
        },
      ],
      warning_days: 30,
    },
    {
      key: 'flight',
      label: 'Flight',
      short_label: 'Flight',
      order: 6,
      enabled: true,
      statuses: [
        { value: 'in_process', label: 'Ticket booked' },
        { value: 'completed', label: 'Departed' },
        { value: 'rejected', label: 'Cancelled' },
      ],
      fields: [
        {
          name: 'step_date',
          label: 'Booking date',
          type: 'date',
          max: null,
          in_details: false,
          required_for: ['in_process', 'completed', 'rejected'],
        },
        {
          name: 'airline',
          label: 'Airline',
          type: 'text',
          max: 100,
          in_details: true,
          required_for: ['in_process', 'completed'],
        },
        {
          name: 'flight_no',
          label: 'Flight number',
          type: 'text',
          max: 20,
          in_details: true,
          required_for: ['in_process', 'completed'],
        },
        {
          name: 'departure_date',
          label: 'Departure date',
          type: 'date',
          max: null,
          in_details: true,
          required_for: ['in_process', 'completed'],
        },
        {
          name: 'ticket_pnr',
          label: 'Ticket PNR',
          type: 'text',
          max: 20,
          in_details: true,
          required_for: [],
        },
      ],
      warning_days: 30,
    },
  ],
}

/** A /workflow/summary response with six steps. */
export const WORKFLOW_SUMMARY = {
  steps: WORKFLOW_CONFIG.steps.map(({ key, label, short_label, order, enabled }) => ({
    key,
    label,
    short_label,
    order,
    enabled,
  })),
  step1: { total_all: 30, total_active: 28, incomplete: 3 },
  step2: { pending: 7, fit: 5, expiring_soon: 1, expired: 2, unfit: 4 },
  step3: { enabled: true, ready: 3 },
  stages: {
    medical: { total: 11, pending: 7, unfit: 4 },
    calling: { total: 6, waiting: 3, in_process: 2, rejected: 1 },
    visa: { total: 4, waiting: 1, in_process: 3, rejected: 0 },
    bmet: { total: 2, waiting: 2, in_process: 0, rejected: 0 },
    flight: { total: 1, waiting: 0, in_process: 1, rejected: 0 },
  },
  completed: 9,
}
